### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by allanlaal** [SimonAlling/better-facebook-messenger#1]
is this abandoned?

the userscript does not work with current Messenger

**Comment by SimonAlling** [comment]
Well ... not officially. But I haven't used it in a while. Facebook have probably updated class names and the like, breaking BFM, which relies heavily on their auto-generated class names:

```javascript
const CLASS_FACEBOOK_CHAT_PHOTO_WRAPPER = "_4yp6"; // wrapper for image in the chat on Facebook.com
const CLASS_FACEBOOK_CHAT_PHOTO = "_4yp9"; // image in the chat on Facebook.com
const CLASS_MESSENGER_CHAT_PHOTO = "_4tsk"; // image in the chat on Messenger.com
const CLASS_MESSENGER_SHARED_PHOTO = "_3m31"; // thumbnail for a shared photo on Messenger.com
```

**Comment by SimonAlling** [comment]
I tried it now, and the main feature – hiding GIFs unless hovered on – still works for me on both Facebook.com and Messenger.com, in Firefox with Violentmonkey on Windows. Could you perhaps share more details about what doesn't work and your system (including OS, browser and userscript add-on)?
